WEBHOOK_URL=
WEBHOOK_API_KEY=
BACKEND_UPLOAD_URL=
BACKEND_UPLOAD_ADMIN_KEY=

docker run -p 8000:8000 \
    -v ./checkpoints:/app/checkpoints \
    -e WEBHOOK_URL=$WEBHOOK_URL \
    -e WEBHOOK_API_KEY=$WEBHOOK_API_KEY \
    -e BACKEND_UPLOAD_URL=$BACKEND_UPLOAD_URL \
    -e BACKEND_UPLOAD_ADMIN_KEY=$BACKEND_UPLOAD_ADMIN_KEY \
    uncensored-tts:latest
